# Generated by Django 4.1.7 on 2024-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('phone', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
