# Generated by Django 5.0.6 on 2024-05-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_user_id_user_id'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('check_in', models.DateField(blank=True)),
                ('check_out', models.DateField(blank=True)),
                ('created_date', models.DateField(blank=True, default=None)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
    ]
