# Generated by Django 5.0.6 on 2024-05-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_hotelbook'),
        ('booking', '0003_remove_hotel_rooms_hotel_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbook',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.roomsavailable'),
        ),
    ]
