# Generated by Django 5.0.6 on 2024-05-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_hotelbook_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbook',
            name='check_in',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='check_out',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='created_date',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
