# Generated by Django 5.0.6 on 2024-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_hotelbook_check_in_alter_hotelbook_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbook',
            name='check_in',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='check_out',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='created_date',
            field=models.DateField(default=None, max_length=50),
        ),
    ]
