# Generated by Django 5.0.6 on 2024-05-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_hotelbook_check_in_alter_hotelbook_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbook',
            name='created_date',
            field=models.DateField(auto_now_add=True, max_length=50),
        ),
    ]
