# Generated by Django 5.0.6 on 2024-05-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_hotelbook_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbook',
            name='room',
        ),
    ]
