# Generated by Django 5.0.6 on 2024-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_hotelbook_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbook',
            name='room',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='hotel_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
