# Generated by Django 5.0.6 on 2024-05-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightsAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(default=None, max_length=50)),
                ('flight_class', models.CharField(default='Economy', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_type', models.CharField(default=None, max_length=50)),
                ('number_of_guest', models.IntegerField(default=0)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AirportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default=None, max_length=250)),
                ('location', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(blank=True, default=None)),
                ('flight_available', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking.flightsavailable')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(default=None, max_length=50)),
                ('rating', models.CharField(default=None, max_length=20)),
                ('description', models.TextField(blank=True, default=None)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomsavailable')),
            ],
        ),
    ]
