# Generated by Django 5.0.6 on 2024-05-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_hotel_rooms_hotel_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsavailable',
            name='room_image',
            field=models.ImageField(default=None, upload_to='room_images/'),
        ),
    ]
